### ISSUE TITLE
安装提交后4000端口，输入问题web提示error

### ISSUE THREAD

**Issue by TTTsuperpyer** [finishy1995/effibot#3]
安装提交后4000端口，输入问题提示error，新加坡节点
![image](https://user-images.githubusercontent.com/63111979/230538468-b77ae47c-c608-439f-a241-313739b09bd5.png)

![image](https://user-images.githubusercontent.com/63111979/230538414-2543a093-a81f-4181-b79e-9e898fdd820c.png)
![image](https://user-images.githubusercontent.com/63111979/230538437-92b3179d-4b09-4bde-882d-c8e6a45c1447.png)

**Comment by finishy1995** [comment]
从截图上看，没有发现明显异常。唯一疑问的点，在于客户端的监听（4001）并未在第二张截图中显示。目前要求客户端和服务器部署在同一个机器内。如果想要分开部署，则需要查看 readme 中自定义开发/部署中的内容。

建议：
1. 检查客户端容器 effibot-demo 是否和 effibot 在一个虚机内启动。
2. F12 或者右键打开客户端的调试窗口，将控制台选项卡中的报错截图/复制发出来
3. 在新加坡虚拟机/物理机的环境内，执行 `docker logs effibot | grep "error"`，这条命令将会查询并筛选出 effibot 的错误日志。你可能需要根据实际环境（可通过 `docker ps -a | grep "effibot"`）,查看 effibot 的实际名称，替换 docker logs xxx

在查看日志后，如果还有疑问，可以将日志贴出来，我会帮忙分析

**Comment by TTTsuperpyer** [comment]
![image](https://user-images.githubusercontent.com/63111979/230562478-a1ac55e6-7fde-4415-aee9-8fdbb27cf47a.png)
![image](https://user-images.githubusercontent.com/63111979/230562530-3585f144-482c-45da-89c4-1fe777a952d5.png)
![image](https://user-images.githubusercontent.com/63111979/230562724-9a30f414-bff6-46a6-b2cf-c921ff57399c.png)

effibot_effibot_1 没启动，查看log是找不到key,可我事实上key是填入了。

**Comment by finishy1995** [comment]
> ![image](https://user-images.githubusercontent.com/63111979/230562478-a1ac55e6-7fde-4415-aee9-8fdbb27cf47a.png) ![image](https://user-images.githubusercontent.com/63111979/230562530-3585f144-482c-45da-89c4-1fe777a952d5.png) ![image](https://user-images.githubusercontent.com/63111979/230562724-9a30f414-bff6-46a6-b2cf-c921ff57399c.png)
> 
> effibot_effibot_1 没启动，查看log是找不到key,可我事实上key是填入了。

你的第12行不符合 Yaml 的格式要求，Yaml 要求空行对齐，Token 前应该空四个空格。你可以参考示例yaml，确保空格正确

**Comment by finishy1995** [comment]
参考格式如下
```yaml
...
Spec:
  GPT:
    Token: "sk-xxxxxxxx"
    Timeout: 20s
    ...
```

**Comment by TTTsuperpyer** [comment]
![image](https://user-images.githubusercontent.com/63111979/230578239-e847c60d-84d6-43a2-a707-bdb932baf704.png)
可以了感谢，但是好像API都需要收费吗？

**Comment by finishy1995** [comment]
> ![image](https://user-images.githubusercontent.com/63111979/230578239-e847c60d-84d6-43a2-a707-bdb932baf704.png) 可以了感谢，但是好像API都需要收费吗？

关于 OpenAI 的收费问题建议查看官网。提供免费的测试额度
